### ISSUE TITLE
Add pagination to admin table and sponsored org table

### ISSUE THREAD

**Issue by s-iloo** [hack4impact-calpoly/ecologistics-portal#143]
**Description**
Add pagination functionality to both admin table and sponsored org table. Essentially, render ~15 rows before splitting them up into pages (adjust number of rows as you see fit). Reference Tanstack docs. 

**Acceptance Criteria**

Steps:

- Add pagination functionality to admin table
- Add pagination functionality to sponsored org table

**Comment by lukewaltz** [comment]
This functionality already seems to be implemented. The only catch is you can't change the number of rows per page.
