### ISSUE TITLE
Define status enum and creating corresponding badge components

### ISSUE THREAD

**Issue by ryanhu021** [hack4impact-calpoly/ecologistics-portal#52]
**Description**
Reimbursements have a `status` field to track the approval status. We want to make sure this field only contains a limited range of values.

**Acceptance Criteria**
Create a `Status` enum with four values:

- Pending = "PENDING"
- OnHold="ON_HOLD"
- Declined="DECLINED"
- Paid="PAID"

Next, create a `StatusBadge` component that takes `ReimbursementStatus` as a prop and returns the corresponding badge as shown in the figma.

Steps:

- Define enum in `/lib/enum.ts`
- Create status badge component

**Comment by tarannssingh** [comment]
Hi Ryan. I believe my code for issue 52 is already merged with main.

**Comment by ryanhu021** [comment]
ah oops my bad
